### ISSUE TITLE
Edges with multiple _from _to targets - multi selection instead of single choice

### ISSUE THREAD

**Issue by rustama** [hackolade/ArangoDB#2]
Hi, currently in ArangoDB is possible to create edge without "hard"-binding it to specific 2 collections.
Meaning that given following collections: A B C
We can use one edge for all types of A-B and B-C and A-C connections.
Just because there is no restrictions on it in the DB.
But in the plugin, when defining the Edge  you can select only one collection as _from target, and only one as _to target.
Please align to the DB, making it multiple choice.
Thank You.

**Comment by pdesmarets** [comment]
Thanks for your comment!  Can you point to documentation showing that _from and _to can have multiple normal collections in each, as this is not obvious from the documentation: https://www.arangodb.com/docs/stable/graphs-edges.html  That would greatly help us.

FYI, the plugin is not yet officially released, but all feedback to improve it is welcome!  Thanks.

**Comment by rustama** [comment]
Hi, not sure if it is documented. But it is actual feature in the db.

There are no restrictions in documentation on this subject.

So if we can use one edge for connection between different collections.
This is the fact in db.
Thank You for fast response

**Comment by pdesmarets** [comment]
OK, do you have a concrete example of how you would use that capability?  An example use case?  I'd love to understand so we can adapt!  Thanks!

**Comment by pdesmarets** [comment]
I see indeed how technically, you can indeed put references to any normal collection within the same edge collection.  Is there a performance benefit to doing that, rather than conceptually separate edge documents in different edge collections, 1 per concept?  Another motivation?

**Comment by rustama** [comment]
For example, if we have several collections, that we need just to connect
them, in graph, for "walking", and the edge attributes are actually only
from and to, we can use one edge to connect them all.
Otherwise, we would need to duplicate same edge (same name even) for each
pair.

Collections: Car, Tv, Camera, Vendor
Edge: MadeBy

From Vendor to any of Car, Camera, Tv

**Comment by rustama** [comment]
I dont think it has performance advantage, but allows to group edges with
same attributes, to a "connection" of specific type. Like in example, so
MadeBy is defined only once, and can accept any collection that describes
products.

**Comment by pdesmarets** [comment]
We're working on introducing a new feature for graph plugins whereby the user could define a node (class) with multiple sub-nodes (sub-classes).  Would that work for you?  You would define a node "item/product" with sub-nodes "Car", "Tv", "Camera".  Then you would have a single edge going from "Vendor" to "item/product" and the other 3 would be inherited.  Would that help, or not?

**Comment by rustama** [comment]
Maybe. Depends on how it will be corelated to ArangoDb. In forwarding and
reversing.

Also, it is less straightforward, and not natively to ArangoDb.

But it is generic approach which is good.
The logical problem that Car, Tv .. are not "sub" to Vendor.

See tags collections for example, tags can be also connected to each
product, and also to vendor.

**Comment by pdesmarets** [comment]
For sure, Car, Tv, Camera, are not sub to Vendor.  

Would you actually have a "normal" collection for each: Car, Tv, Camera?  Or a single one?

We still need to do forward- and reverse-engineering, indeed.  Better to know this ahead of that development!  In any case, wince we're working on this directly with ArangoDB, I'll ask the question.  There had been no objection from their side on this point...

**Comment by rustama** [comment]
Each of them is normal collection.
They all describing some products, and each of them, can have Vendor, Tags
and others. So there are many connections bteween any of the product to
Vendor or others

**Comment by pdesmarets** [comment]
OK, got it.  We need to think through a viable solution.  Thanks for the feedback!!!

**Comment by rustama** [comment]
Thank For Yor Effort.
We are checking ArangoDb and Hackolade so we are going to use such olugin
heavily.
Be in touch

**Comment by pdesmarets** [comment]
Got a response back from ArangoDB, which is pretty much in line with the feature currently in development: "The ability to have multiple collections in the _from and _to of and edge is mirrored in RDF/RDFS/Owl where an objectType property can have multiple domain (from) classes and multiple range (to) classes can be specified.   The reason I bring this up, is that RDF/RDFS/OWL creates equivalence classes for the multi-domain and multi-range. In other words the inference is saying that there is an unnamed abstract superclass, for those classes that appear together in the from and to. You can think of this in an analogous way in ArangoDB:  the multiple vertex collections referenced in the from and to also form equivalence classes and they most likely arise because ArangoDB does not directly implement inheritance.  So conceptually one could think of them as an equivalence class  in ArangoDB and the closest thing to that is a UNION of collections. You see similar artifacts in relational models, for example the categorization pattern."

And as mentioned, forward- and reverse-engineering must be in sync with the modeling approach.

**Comment by rustama** [comment]
Ok, will check this out.
Thank You

**Comment by rustama** [comment]
Hi, can I ask You, what is proper way to copy/past collections between
models? Is there a way to store collection as file and then reuse it via
definition or just import?

We want to share same collections between different models of database.

**Comment by pdesmarets** [comment]
Several possibilities here.  You may start multiple instances of Hackolade and copy/paste between them.  But the proper way to handle reusable objects is through definitions, described here: https://hackolade.com/help/Reusableobjectsdefinitions.html

If I may suggest, we have a support system with ticketing (and better follow-up) at support@hackolade.com
